Added check for dataset creation, removed compute notify hardcoding
cisco-open/flame pull request #200
Opened 2022-07-29 04:43 UTC by dhruvsgarg

This pr ensures that the compute or region specified in dataset realm actually exists. Right now the compute and region are checked for exact match. In a future pr, the region will also match based on other subregions and still map the dataset to the correct computeIds.

The pr also uses the registered datasets to correctly identify and notify the required computes for deploying tasks of a job.

2022-07-29 05:47 UTC, myungjin requested changes
Left several comments.Two independent things handled in one PR. Since compute notify hardcoding fix is incorrect, it is better to focus on dataset creation check and to remove compute notify hardcoding fix.

2022-07-29 05:47 UTC, myungjin commented on cmd/controller/app/database/mongodb/compute.go
> +func (db *MongoService) CheckComputeByRegion(region string) ([]string, error) {
The function name is misleading. How about the following?
```suggestion
func (db *MongoService) GetComputesByRegion(region string) ([]string, error) {
```

2022-07-29 05:47 UTC, myungjin commented on cmd/controller/app/database/mongodb/compute.go
> +	// TODO send more computeIds instead of just one. Let the calling code decide which computeId to use
Parsing more than one doc shouldn't be too hard.
Please consider to finish the implementation instead of leaving TODO.

Some example code can be found https://github.com/cisco-open/flame/blob/main/cmd/controller/app/database/mongodb/job.go#L123

2022-07-29 05:47 UTC, myungjin commented on cmd/controller/app/database/mongodb/compute.go
> +func (db *MongoService) GetComputeRegion(computeId string) (string, error) {
Instead of returning `region` string only, perhaps returning `ComputeSpec` is more useful for future use.

The caller of this function can determine which attributes in ComputeSpect to use. Here we can keep DB API relatively simple.

If you decide to return the whole ComputeSpec, please rename the function (e.g., `GetCompute` or `GetComputeById`)

2022-07-29 05:47 UTC, myungjin commented on cmd/controller/app/job/default_handler.go
> +	// TODO implement for FromUser datasets
`FromUser` doesn't need notification because bringing up compute resource is responsibility of user.

2022-07-29 05:47 UTC, myungjin commented on cmd/controller/app/job/default_handler.go
> +	fromSystemDatasets := h.jobSpec.DataSpec.FromSystem
notification shouldn't be based on datasets. It should be based on tasks in the task collection given a job ID.

I think we talked about this before. I thought that when task is created in DB, task will have a compute ID in its DB record.
So, when tasks are retrieved, compute ID can be obtained too.
There is no need to go through datasets.

Also, the key issue with this implementation is that tasks of roles (e.g., aggregator) that `isDataConsumer` flag is unset won't be notified at all.

2022-07-29 05:47 UTC, myungjin commented on pkg/openapi/controller/api_datasets_service.go
> +	isRegion := strings.HasPrefix(datasetRealm, "default/")
what if datasetRealm is just "default"?

Also, define a constant, say `RootRealm` or `DefaultRealm` instead of hardcoded value.

2022-07-29 05:47 UTC, myungjin commented on pkg/openapi/controller/api_datasets_service.go
> +		datasetInfo.Realm = datasetRealm + "/" + eligibleComputes[0]
use path.join instead of string concatenation.

See example: https://pkg.go.dev/path#example-Join

2022-07-29 05:47 UTC, myungjin commented on pkg/openapi/controller/api_datasets_service.go
> +		datasetInfo.Realm = computeRegion + "/" + datasetRealm
same here. use path.join

2022-08-01 04:49 UTC, myungjin reviewed
comments are left. Please consider to address them.

2022-08-01 04:49 UTC, myungjin commented on pkg/openapi/controller/api_datasets_service.go
> +		if len(eligibleComputes) == 0 {
If no document is found in mongodb (from the call of `GetComputesByRegion`), I thought mongodb raises an error of mongo.ErrNoDocuments. Do you assume that there can be a case where going through a cursor ended up with empty list?

Also, if mongo.ErrNoDocuments is raised, this line (line 75) will never be executed. Is this what you expect?

If you think empty list is an error case, perhaps it's better to handle it within GetComputesByRegion and here you should skip the checking the size of the list.

2022-08-01 04:49 UTC, myungjin commented on pkg/openapi/controller/api_datasets_service.go
> +	if isRegion {
Overall, the section of `if isRegion else` is too complex since it has three nested `if` statements. One way to reduce the complexity is to further introduce sub-function(s).

If you introduce sub-functions, please also consider to write some unit test cases..

2022-08-01 04:49 UTC, myungjin commented on pkg/openapi/controller/api_datasets_service.go
> +	// Might move defaultRealm const to another file or utils later since it will also be used for compute registration.
Looks like you already did so with util.DefaultRealm. Please remove this comment.

2022-08-01 04:49 UTC, myungjin commented on pkg/openapi/controller/api_datasets_service.go
> +			// No compute found for the given region. If dataset is public, set compute to DefaultRealm
Where do you set DefaultRealm if dataset is public? I couldn't find any line to do so. Am I missing something here?

2022-08-01 04:49 UTC, myungjin commented on pkg/openapi/controller/api_datasets_service.go
> +			// No compute found for given computeId. If dataset is public, set compute to DefaultRealm
Same here. Where do you set DefaultRealm in case dataset is public?

2022-08-01 21:23 UTC, dhruvsgarg commented on pkg/openapi/controller/api_datasets_service.go
> +			// No compute found for the given region. If dataset is public, set compute to DefaultRealm
Okay right, there was a gap in the previous implementation. For public datasets, if the realm doesnt match the compute infra, we want to retain the dataset's realm (for our TAG) but assign it to a default compute. I have updated the code to use a `computeFound` bool variable in the `DatasetInfo` component. This variable will be true if a matching computeId OR a computeId in the given region is found. Thus, when creating a task, we check if computeFound is true. If it is not true, we assign it the defaultRealm's compute.

2022-08-02 16:29 UTC, dhruvsgarg commented on pkg/openapi/controller/api_datasets_service.go
> +		if len(eligibleComputes) == 0 {
I have updated the implementation to return an empty string list from `GetComputeIdsByRegion` if there is any mongodb error in fetching documents. Hence, if ErrNoDocuments is encountered, an empty string list will be returned. along with the error message. This way we can just check for computes by region once, and assign compute accordingly.

2022-08-02 21:07 UTC, dhruvsgarg commented on pkg/openapi/controller/api_datasets_service.go
> +	if isRegion {
I created the functions but couldn't write test cases since these functions also use the DBService. If you suggest a way, I can include these test cases in the next PR

2022-08-03 01:00 UTC, myungjin reviewed
the revision is almost there. please consider to address a few comments.

2022-08-03 01:00 UTC, myungjin commented on pkg/openapi/controller/api_datasets_service.go
> +	if isRegion {
One way is to create a mock interface of DBService; let's not worry about it here as the sub-functions look much clearer.

2022-08-04 00:51 UTC, myungjin approved these changes
one minor issue to think about. But overall lgtm.

2022-08-04 00:51 UTC, myungjin commented on pkg/openapi/controller/api_datasets_service.go
> +	eligibleComputes, err := s.dbService.GetComputeIdsByRegion(datasetRealm)
There is no check on `err`. Is this safe or can the error be ignored? If so, you may need to change it to something like the following:

```
eligibleComputes, _ := s.dbService.GetComputeIdsByRegion(datasetRealm)
```

2022-08-04 00:51 UTC, merged