CI/CD add github publish action on release to push docker image
cisco-open/flame pull request #268
Opened 2022-11-15 20:19 UTC by Divlik

2022-11-15 21:22 UTC, myungjin reviewed
left a few comments. Also, please add description in your commit with `git commit --amend`

2022-11-15 21:22 UTC, myungjin commented on Dockerfile
> +FROM golang:1.16-alpine
Do we need this? This is just an example. Now that the build/Dockerfile is working fine, I guess this is not needed. Can you share your opinion?

2022-11-15 21:22 UTC, myungjin commented on main.go
> +package main
The same comment here. Do we need this toy example? Otherwise, please remove it.

2022-11-15 21:22 UTC, myungjin commented on .github/workflows/publish.yml
> +        uses: docker/setup-qemu-action@v2
Is this really needed? what is the benefit of qemu support? If this is not absolutely needed, please remove it.

2022-11-16 15:41 UTC, Divlik commented on .github/workflows/publish.yml
> +        uses: docker/setup-qemu-action@v2
This is to support multiple platform build, since we are not building for other platforms right now this can be safely removed.

2022-11-16 15:41 UTC, Divlik commented on main.go
> +package main
updated

2022-11-16 16:37 UTC, myungjin requested changes
please update commit comments.

2022-11-16 18:00 UTC, myungjin approved these changes
lgtm

2022-11-16 18:00 UTC, merged