Create a run minikube script
cisco-open/flame pull request #363
Opened 2023-03-08 17:38 UTC by alexandruuBytex

## Description

Please provide a meaningful description of what this change will do, or is for. Bonus points for including links to
related issues, other PRs, or technical references.

Note that by _not_ including a description, you are asking reviewers to do extra work to understand the context of this
change, which may lead to your PR taking much longer to review, or result in it not being reviewed at all.

## Type of Change

- [ ] Bug Fix
- [ X ] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [ ] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [ ] Existing issues have been referenced (where applicable)
- [ ] I have verified this change is not present in other open pull requests
- [ ] Functionality is documented
- [ ] All code style checks pass
- [ ] New code contribution is covered by automated tests
- [ ] All new and existing tests pass

2023-03-08 18:55 UTC, myungjin submitted a review, later dismissed
lgtm

2023-03-09 15:36 UTC, myungjin reviewed
Please consider to address my comment.

2023-03-09 15:36 UTC, myungjin commented on .github/workflows/presubmits.yml
> +        args: --skip-files ".*(pkg\/openapi\/api_design_schemas\.go)|(pkg\/openapi\/api_jobs\.go).*"
Instead of changing this, please consider to update the following config file and see if that works.

https://github.com/cisco-open/flame/blob/main/.golangci.yml

More specifically, we would like to add exception for `dupl` check. So, refer to the following lines: https://github.com/cisco-open/flame/blob/main/.golangci.yml#L129-L132.

And refer to https://golangci-lint.run/usage/configuration/ as well.

2023-03-09 16:57 UTC, alexandruuBytex commented on .github/workflows/presubmits.yml
> +        args: --skip-files ".*(pkg\/openapi\/api_design_schemas\.go)|(pkg\/openapi\/api_jobs\.go).*"
I tried adding the files to the extrude-rules field but it didn't worked. I work if I add the files skip-files field.

2023-03-09 17:00 UTC, myungjin requested changes
please consider my comments.

2023-03-09 17:00 UTC, myungjin commented on .github/workflows/presubmits.yml
> +      uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376 # v3
revert this change. Don't create this unnecessary change.

2023-03-09 17:07 UTC, myungjin commented on .github/workflows/presubmits.yml
> +        args: --skip-files ".*(pkg\/openapi\/api_design_schemas\.go)|(pkg\/openapi\/api_jobs\.go).*"
Can you try the following?
```
    - path: pkg/openapi/api_design_schemas.go
      linters:
        - dupl
    - path: pkg/openapi/api_jobs.go
      linters:
        - dupl
```

2023-03-09 17:12 UTC, myungjin requested changes
please refer to my earlier comments.

2023-03-10 17:38 UTC, myungjin approved these changes
lgtm

2023-03-13 08:46 UTC, merged