Merge research branch code
cisco-open/flame pull request #368
Opened 2023-03-14 14:11 UTC by alexandruuBytex

## Description

Please provide a meaningful description of what this change will do, or is for. Bonus points for including links to
related issues, other PRs, or technical references.

Note that by _not_ including a description, you are asking reviewers to do extra work to understand the context of this
change, which may lead to your PR taking much longer to review, or result in it not being reviewed at all.

## Type of Change

- [ ] Bug Fix
- [ ] New Feature
- [ ] Breaking Change
- [ X ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [ ] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [ ] Existing issues have been referenced (where applicable)
- [ ] I have verified this change is not present in other open pull requests
- [ ] Functionality is documented
- [ ] All code style checks pass
- [ ] New code contribution is covered by automated tests
- [ ] All new and existing tests pass

2023-03-15 14:42 UTC, elqurio commented
The SDK changes no longer seem to be a part of this PR. Should I add them?

2023-03-16 01:47 UTC, myungjin commented on scripts/runMinikube.sh
> +#!/usr/bin/env bash
Why is this file in this PR? This was already merged into the main branch. Please remove it.

2023-03-16 01:56 UTC, myungjin requested changes
This PR contains the changes which were already merged in the main branch. It can't be approved as is.

2023-03-16 01:56 UTC, myungjin commented on examples/parallel_experiment/parallel_experiment.zip
Why does this file need to be updated? Does your change require code update as well? If so, why do other examples not have zip files updated?

2023-03-16 01:56 UTC, myungjin commented on lib/python/flame/examples/async_mnist/aggregator/config.json
> +        {
This is also already included in the main branch. This is not the change that should be included in this PR.

2023-03-16 01:56 UTC, myungjin commented on lib/python/flame/examples/async_mnist/trainer/config1.json
> +            "host": "localhost",
same here!

2023-03-16 01:56 UTC, myungjin commented on lib/python/flame/examples/async_mnist/trainer/config2.json
> +            "host": "localhost",
same here

2023-03-16 01:56 UTC, myungjin commented on lib/python/flame/examples/async_mnist/trainer/config3.json
> +            "host": "localhost",
same here

2023-03-16 01:56 UTC, myungjin commented on lib/python/flame/examples/async_mnist/trainer/config4.json
> +            "host": "localhost",
same here

2023-03-16 10:56 UTC, alexandruuBytex commented on examples/parallel_experiment/parallel_experiment.zip
Only the name of the file have been changed in order to work with the runExample script. The zip file must have the same name as the example.

2023-03-16 10:56 UTC, alexandruuBytex commented on lib/python/flame/examples/async_mnist/aggregator/config.json
> +        {
I removed the change.

2023-03-16 10:56 UTC, alexandruuBytex commented on lib/python/flame/examples/async_mnist/trainer/config4.json
> +            "host": "localhost",
I removed the change.

2023-03-16 11:08 UTC, alexandruuBytex commented on scripts/runMinikube.sh
> +#!/usr/bin/env bash
The file have been removed.

2023-03-16 11:40 UTC, elqurio approved these changes

2023-03-16 11:52 UTC, openwithcode approved these changes

2023-03-16 11:53 UTC, openwithcode approved these changes

2023-03-16 11:57 UTC, openwithcode approved these changes

2023-03-22 15:49 UTC, closed without merging