Add per-channel backend support
cisco-open/flame pull request #373
Opened 2023-03-21 18:04 UTC by alexandruuBytex

## Description

Added support for per-channel backend and validation for the new  schema. The schema can be found here:
https://cisco-my.sharepoint.com/:w:/r/personal/myungjle_cisco_com/_layouts/15/doc2.aspx?sourcedoc=%7B3e2e76ec-c7aa-4809-8684-4c4c7560acbb%7D&action=edit&cid=b5ac408e-11dd-4fa8-a0e5-e7efb8452c5d

## Type of Change

- [ ] Bug Fix
- [ x ] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [ ] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [ ] Existing issues have been referenced (where applicable)
- [ ] I have verified this change is not present in other open pull requests
- [ ] Functionality is documented
- [ ] All code style checks pass
- [ ] New code contribution is covered by automated tests
- [ ] All new and existing tests pass

2023-03-22 08:18 UTC, openwithcode requested changes

2023-03-22 08:18 UTC, openwithcode commented on cmd/controller/app/job/builder.go
> +	var jobBackend string = string(b.jobSpec.Backend)
We should not cast it to string, but we should compare if the value contained in the b.jobSpec.Backend is one of the valid types

2023-03-22 08:18 UTC, openwithcode commented on cmd/controller/app/job/builder.go
> +		incompleteChannels = append(incompleteChannels, channel)
Is this really useful ?

2023-03-22 08:18 UTC, openwithcode commented on cmd/controller/app/job/builder.go
>  func (b *JobBuilder) build() ([]objects.Task, []string, error) {
Please export the changes to a separate function that cares of per channel checks

2023-03-22 08:18 UTC, openwithcode commented on cmd/controller/app/job/builder.go
> +	if len(brokers) < len(incompleteChannels) {
This is not really correct as we can have a single broker for many channels

2023-03-22 08:18 UTC, openwithcode commented on cmd/controller/app/job/builder.go
> +	if jobBackend == "" && len(incompleteChannels) > 0 {
backend is optional.
If is not specified then we need to choose a random one from the broker list that we have. This is applied only if the user doesn't specify the backend for at least one of the channels

2023-03-22 08:18 UTC, openwithcode commented on cmd/controller/app/job/builder.go
> +				validBackendFound = true
the for loop should be stopped after the backend it's matched

2023-03-22 08:18 UTC, openwithcode commented on cmd/controller/app/job/builder.go
> +			validBackendFound = true
same as above

2023-03-22 08:18 UTC, openwithcode commented on cmd/controller/app/job/builder.go
> +	for index, channel := range incompleteChannels {
I don't think that we should populate the backend and host for every channel as it's not really applied based on the design schema we have.
We have to add it from schema.json to the generated config file if is specified

2023-03-22 09:49 UTC, alexandruuBytex commented on pkg/openapi/model_channel.go
> +	Host string `json:"host"`
Should I change host into broker host in the json file too?

2023-03-22 11:11 UTC, openwithcode commented on pkg/openapi/model_channel.go
> +	BrokerHost string `json:"host"`
the json tag `host` should be renamed as well

2023-03-22 11:38 UTC, alexandruuBytex commented on examples/mnist/dataSpec.json
> -    "fromUser": {
I installed it and updated the file. I was using a tab size of 4 spaces in the vs code settings but another setting was overwriting the first one.
Now it seems to work properly.

2023-03-22 11:45 UTC, openwithcode requested changes

2023-03-22 11:45 UTC, openwithcode commented on cmd/controller/app/job/builder.go
> +	if err := b.perChannelBackendCheck(); err != nil {
Maybe we can add this directly in the setup method

2023-03-22 11:45 UTC, openwithcode commented on examples/mnist/dataSpec.json
> -    "fromUser": {
The formatting is still applied to this file. Please revert the change

2023-03-22 11:45 UTC, openwithcode commented on examples/mnist/job.json
> -    "designId": "mnist",
please revert  the formatting change here as weell

2023-03-22 11:45 UTC, openwithcode commented on examples/mnist/schema.json
> -    "name": "A simple example schema v1.0.0",
revert the formatting changes of this file

2023-03-22 14:18 UTC, openwithcode requested changes

2023-03-22 14:18 UTC, openwithcode commented on cmd/controller/app/job/builder_example_test.go
> +	builder := NewJobBuilder(dbService, config.JobParams{
export the brokers and just reference them as at this point it's a lot of duplicated code

2023-03-22 14:18 UTC, openwithcode commented on cmd/controller/app/job/builder_example_test.go
> +		Brokers: []config.Broker{
same as above

2023-03-22 14:18 UTC, openwithcode commented on cmd/controller/app/job/builder_example_test.go
> +		Brokers: []config.Broker{
same as above

2023-03-22 14:18 UTC, openwithcode commented on cmd/controller/app/job/builder_example_test.go
> +		Brokers: []config.Broker{
same as above

2023-03-22 14:18 UTC, openwithcode commented on cmd/controller/app/job/builder_example_test.go
> +		Brokers: []config.Broker{
same as above

2023-03-22 14:18 UTC, openwithcode commented on cmd/controller/app/job/testdata/asyncfl_hier_mnist/1.json
> +	"brokers": [
formatting is wrong

2023-03-22 14:18 UTC, openwithcode commented on cmd/controller/app/job/testdata/asyncfl_hier_mnist/1.json
> +		{
given the fact that no channel specified any backend, then don't add p2p as it will not be used

2023-03-22 14:18 UTC, openwithcode commented on cmd/controller/app/job/testdata/asyncfl_hier_mnist/2.json
> +	"brokers": [
same as above

2023-03-22 20:47 UTC, myungjin requested changes
I left a few comments. Please address my comments. Reach out if there are any questions regarding my comments.

2023-03-22 20:47 UTC, myungjin commented on pkg/openapi/model_channel.go
> +	BrokerHost string `json:"brokerHost"`
This openapi file is updated with new entries, but I don't see the api specification updated.

If possible, we should avoid manual changes for openapi files. Manual changes can lead to discrepancy between api specification and the implementation.

2023-03-22 20:47 UTC, myungjin commented on pkg/openapi/model_channel.go
> +	BrokerHost string `json:"brokerHost"`
Also, per-channel configuration for backend should be optional. WIthout `omitempty`, this line mandates some value in the field.

2023-03-22 20:47 UTC, myungjin commented on cmd/controller/app/job/builder.go
> +	if err = b.perChannelBackendCheck(); err != nil {
I don't see any code to populate per-channel config. 
Where is the following (
https://github.com/cisco-open/flame/pull/373/files#diff-8f0e65135b23fe5484d3a0972cf2b28d79868c2e7dabd76a7bf8f4773da3063bR32-R34) used?

I don't see any example or test-code to use those two variables.

To address the above questions, I think you should create a control plane example for a lib example https://github.com/cisco-open/flame/tree/main/lib/python/flame/examples/hybrid .

2023-03-25 00:56 UTC, myungjin reviewed
Left a few comments. You can address those after our meeting scheduled on Monday if you are worried about more drastic changes after the meeting.

2023-03-25 00:56 UTC, myungjin commented on api/design_components.partials.yml
> +    brokerHost:
Should this be simply `host` to comply with the design doc you have?

2023-03-25 00:56 UTC, myungjin commented on api/design_components.partials.yml
> +CommBackend:
We already have it defined in `job_components.partials.yml`

take a look at `openapi.yaml.mustache`; all the partials are combined into one file.

So, no need to redefine the same thing here.

2023-03-25 00:56 UTC, myungjin commented on cmd/controller/app/job/builder.go
> +func (b *JobBuilder) perChannelBackendCheck() error {
We shouldn't try to fix any input error. This function tries to check error and fix it. But the function name only suggests that it's checking the error. Anyway, we shouldn't try to fix input error here, IMO.

Also, checking errors in the input should be done somewhere else; for example in preCheck function.

I believe that what we want is to write user-fed per-channel broker and host into config.json (the config used by the lib code) if they are specified in schema.json.

If they (per-channel broker and host) don't exist in the channel section, we simply don't write anything.

I think we should treat it as an error if jobBackend is not specified.

2023-03-25 00:56 UTC, myungjin commented on cmd/controller/app/job/builder.go
> +	}
Again, re lines 205-207, let's not complicate things.

We don't need to worry about jobBackend is given or not in order to decide whether populating per-channel configuration is needed or not.

If user provides per-channel broker and host, then we will write them into configj.json. Otherwise, we do nothing.

When per-channel broker and host are given, validating them is a separate issue. checking jobBackend is not empty is also a separate issue.

2023-03-27 21:52 UTC, myungjin requested changes
left a few comments. please consider to fix them.

2023-03-27 21:52 UTC, myungjin commented on pkg/openapi/model_job_spec.go
> +	Backend       CommBackend `json:"backend"`
Before manually modifying files under pkg/openapi folder, reconsider if these auto-generated files must be manually updated or not and see if there is a way to avoid that.

If we start to manually update those files, it will become hard to maintain the consistency between api specification and the actual code. Also, later if those files need to be generated again, the manual changes applied to them will not be reflected and it will become hard to track the changes and do them correctly. @openwithcode, this is also FYI.

For this particular case, you need to set backend as required field: https://github.com/cisco-open/flame/blob/main/api/job_components.partials.yml#L53.

2023-03-27 21:52 UTC, myungjin commented on cmd/controller/app/job/testdata/hybrid/1.json
> +{
1.json and 2.json are not configs for the hybrid exmaple. Here are five files you need to refer to.

https://github.com/cisco-open/flame/blob/main/lib/python/flame/examples/hybrid/trainer/config_eu_org1.json
https://github.com/cisco-open/flame/blob/main/lib/python/flame/examples/hybrid/trainer/config_eu_org2.json
https://github.com/cisco-open/flame/blob/main/lib/python/flame/examples/hybrid/trainer/config_us_org1.json
https://github.com/cisco-open/flame/blob/main/lib/python/flame/examples/hybrid/trainer/config_us_org2.json
https://github.com/cisco-open/flame/blob/main/lib/python/flame/examples/hybrid/aggregator/config.json

2023-03-27 21:52 UTC, myungjin commented on examples/hybrid/README.md
> +## Hybrid
Looking at the config of the example, this example is not one in https://github.com/cisco-open/flame/tree/main/lib/python/flame/examples/hybrid.

This example can't run the hybrid example that we need to support in this example.

Once the hybrid example is created, update the document correctly. For example, if the example is executed correctly, five agents will be created, not three (https://github.com/cisco-open/flame/pull/373/files#diff-5cc68a51c3891579d0a70d471ca0ac780545df763566eb12d3509d746f294343R67-R69).

2023-03-30 14:59 UTC, myungjin reviewed
left a couple of messages.

2023-03-30 16:34 UTC, myungjin approved these changes
lgtm

2023-03-30 18:16 UTC, myungjin requested changes
I spotted another issue. this needs to be addressed.

2023-03-30 18:16 UTC, myungjin commented on examples/hybrid/dataSpec.json
> +{
The dataSpec's specification is now updated. See https://github.com/cisco-open/flame/blob/main/examples/mnist/dataSpec.json.

2023-03-30 19:10 UTC, myungjin commented
Since #381 builds on top of this PR, let me close this.

2023-03-30 19:10 UTC, closed without merging