Removal of zip files in examples at the control plane layer
cisco-open/flame pull request #396
Opened 2023-04-10 16:17 UTC by alexandruuBytex

## Description

ZIP files in a repository makes it hard to do version control, test, debug, etc. Remove the zip files and read the trainer, aggregator and the their variations directly.

## Type of Change

- [ ] Bug Fix
- [ x ] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [ ] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [ ] Existing issues have been referenced (where applicable)
- [ ] I have verified this change is not present in other open pull requests
- [ ] Functionality is documented
- [ ] All code style checks pass
- [ ] New code contribution is covered by automated tests
- [ ] All new and existing tests pass

2023-04-10 21:04 UTC, myungjin requested changes
Left several comments. Please also address test errors.

2023-04-10 21:04 UTC, myungjin commented on cmd/flamectl/resources/code/code.go
> +	var zipArchivePath = fmt.Sprintf("%s.zip", params.CodePath)
I guess the whole part that is implemented here can be put as a separate function instead of doing the implementation in the Create() function. That way readability can be improved.

2023-04-11 06:58 UTC, alexandruuBytex commented on cmd/flamectl/resources/code/code.go
> +	"archive/zip"
We still do feed a zip file. We just create and delete the zip file every time and in this way, we make sure the zip file is always using the latest version of the files that are inside. I tried not creating an archive at all but this requires significantly more changes.
Creating and deleting a zip file is the easiest and more stable solution.

2023-04-12 22:08 UTC, myungjin requested changes
Left several comments. Please consider to address them. Let's discuss offline if there is any question.

2023-04-12 22:08 UTC, myungjin commented on cmd/flamectl/resources/code/code.go
> +func CreateZipFile(params Params, pathToSrc, archiveDestination string) error {
See if you can leverage some code regarding zip here: https://github.com/cisco-open/flame/blob/main/pkg/util/zip.go.

The implementation may or may not support the arbitrary sub-directory structures. It should be a good starting point. Let's avoid any redundant effort.

2023-05-05 14:43 UTC, elqurio commented
See - https://github.com/cisco-open/flame/pull/408

2023-05-05 14:43 UTC, closed without merging